CREATE TABLE IF NOT EXISTS purchases (
    journal_no      TEXT        PRIMARY KEY,
    id              INTEGER     NOT NULL,
    doc_type        TEXT        NOT NULL,
    doc_date        TEXT        NOT NULL,
    account_code    TEXT,
    sub_code        TEXT        NOT NULL,
    group1          TEXT,
    tax_invoice1    TEXT,
    tax_invoice     TEXT,
    tax_inv_date    TIMESTAMPTZ,
    ref_no          TEXT,
    remark          TEXT,
    sales_code      TEXT,
    due_date        TIMESTAMPTZ,
    disc_pct        INTEGER     NOT NULL DEFAULT 0,
    disc2           BIGINT      NOT NULL DEFAULT 0,
    warehouse       TEXT,
    commission_pct  INTEGER     NOT NULL DEFAULT 0,
    vat_flag        TEXT,
    total_value     BIGINT      NOT NULL DEFAULT 0,
    vat_amount      BIGINT      NOT NULL DEFAULT 0,
    delivery_note   TEXT,
    ref2            TEXT,
    alt_sub         TEXT,
    total_disc      BIGINT      NOT NULL DEFAULT 0,
    expedition      TEXT,
    packaging       TEXT,
    doc_subtype     TEXT,
    gross_amount    BIGINT      NOT NULL DEFAULT 0,
    is_posted       TEXT,
    is_paid         TEXT,
    group_code      TEXT,
    pph_pct         INTEGER     NOT NULL DEFAULT 0,
    val1            BIGINT      NOT NULL DEFAULT 0,
    control         INTEGER     NOT NULL DEFAULT 1,
    print_count     INTEGER     NOT NULL DEFAULT 0,
    is_printed      INTEGER     NOT NULL DEFAULT 0,
    approved_by     INTEGER,
    period_code     TEXT        NOT NULL,
    register_id     TEXT,
    legacy_source   TEXT,
    changed_by      INTEGER,
    changed_at      TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_purchases_doc_date ON purchases (doc_date);
CREATE INDEX IF NOT EXISTS idx_purchases_period ON purchases (period_code);
CREATE INDEX IF NOT EXISTS idx_purchases_sub ON purchases (sub_code);
