CREATE TABLE IF NOT EXISTS sales (
    journal_no      TEXT        PRIMARY KEY,
    id              INTEGER     NOT NULL,
    doc_type        TEXT        NOT NULL,
    doc_date        TEXT        NOT NULL,
    account_code    TEXT,
    sub_code        TEXT,
    member_code     TEXT,
    point_value     BIGINT      NOT NULL DEFAULT 0,
    card_code       TEXT,
    group1          TEXT,
    ap_journal      TEXT,
    tax_invoice     TEXT,
    tax_inv_date    TIMESTAMPTZ,
    ref_no          TEXT,
    remark          TEXT,
    sales_code      TEXT,
    due_date        TIMESTAMPTZ,
    cashier         TEXT,
    disc_pct        INTEGER     NOT NULL DEFAULT 0,
    disc2_pct       INTEGER     NOT NULL DEFAULT 0,
    warehouse       TEXT,
    shift           TEXT,
    payment_amount  BIGINT      NOT NULL DEFAULT 0,
    vat_flag        TEXT,
    cash_amount     BIGINT      NOT NULL DEFAULT 0,
    non_cash        BIGINT      NOT NULL DEFAULT 0,
    total_value     BIGINT      NOT NULL DEFAULT 0,
    vat_amount      BIGINT      NOT NULL DEFAULT 0,
    change_amount   BIGINT      NOT NULL DEFAULT 0,
    total_disc      BIGINT      NOT NULL DEFAULT 0,
    card_type       TEXT,
    gross_amount    BIGINT      NOT NULL DEFAULT 0,
    voucher_amount  BIGINT      NOT NULL DEFAULT 0,
    credit_amount   BIGINT      NOT NULL DEFAULT 0,
    is_posted       TEXT,
    is_paid         TEXT,
    group_code      TEXT,
    cc_account      TEXT,
    cc_number       TEXT,
    ref2            TEXT,
    alt_sub         TEXT,
    commission_pct  INTEGER     NOT NULL DEFAULT 0,
    control         INTEGER     NOT NULL DEFAULT 1,
    print_count     INTEGER     NOT NULL DEFAULT 0,
    is_printed      INTEGER     NOT NULL DEFAULT 0,
    approved_by     INTEGER,
    period_code     TEXT        NOT NULL,
    register_id     TEXT,
    legacy_source   TEXT,
    changed_by      INTEGER,
    changed_at      TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_sales_doc_date ON sales (doc_date);
CREATE INDEX IF NOT EXISTS idx_sales_period ON sales (period_code);
CREATE INDEX IF NOT EXISTS idx_sales_register ON sales (register_id);
