CREATE TABLE IF NOT EXISTS subsidiaries (
    sub_code        TEXT        PRIMARY KEY,
    name            TEXT        NOT NULL,
    account_code    TEXT,
    contact_person  TEXT,
    credit_limit    BIGINT      NOT NULL DEFAULT 0,
    tax_name        TEXT,
    tax_addr1       TEXT,
    tax_addr2       TEXT,
    address         TEXT,
    city            TEXT,
    country         TEXT,
    npwp            TEXT,
    remark          TEXT,
    remark2         TEXT,
    remark3         TEXT,
    max_value       BIGINT      NOT NULL DEFAULT 0,
    commission_pct  INTEGER     NOT NULL DEFAULT 0,
    last_balance    BIGINT      NOT NULL DEFAULT 0,
    total_in        BIGINT      NOT NULL DEFAULT 0,
    total_out       BIGINT      NOT NULL DEFAULT 0,
    accum_account   TEXT,
    group_code      TEXT        NOT NULL DEFAULT '1',
    disc_account    TEXT,
    phone           TEXT,
    fax             TEXT,
    giro_account    TEXT,
    disc_pct        INTEGER     NOT NULL DEFAULT 0,
    cash_account    TEXT,
    alt_account     TEXT,
    status          TEXT        NOT NULL DEFAULT 'A',
    discount1       BIGINT      NOT NULL DEFAULT 0,
    disc1_pct       INTEGER     NOT NULL DEFAULT 0,
    disc2_pct       INTEGER     NOT NULL DEFAULT 0,
    changed_at      TIMESTAMPTZ,
    changed_by      INTEGER
);
CREATE INDEX IF NOT EXISTS idx_subsidiaries_group ON subsidiaries (group_code);
