-- MOVED: This migration now lives in sinar-makmur-dashboard/supabase/migrations/0032_help_faq_search_rpc.sql
-- The dashboard repo owns the single Supabase migration tree.
-- This file is retained as a redirect; do NOT apply it.
