name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore packages
      run: msbuild Kasir.sln /t:Restore /p:Configuration=Release /p:Platform=x86

    - name: Build solution
      run: msbuild Kasir.sln /p:Configuration=Release /p:Platform=x86 /p:TreatWarningsAsErrors=true

    - name: Setup VSTest
      uses: darenm/Setup-VSTest@v1.3

    - name: Run tests
      run: vstest.console.exe Kasir.Tests\bin\Release\Kasir.Tests.dll
